import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Provider } from 'react-redux';
import store from '@/redux/store';
import ReduxProvider from '@/providers/ReduxProvider';
import { SWRProvider } from '@/providers/SWRProvider';
const inter = Inter({ subsets: ['latin'] });

import './globals.css';

//! 一些配置文件 网站清单的内容
export const metadata: Metadata = {
    title: '1Create Next App',
    description: '1Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <SWRProvider>
                    {/* <ReduxProvider> */}
                    {/* <SessionProvider session={session}> */}
                    <main className="py-24 px-2">
                        main layout
                        <div className="container m-auto">{children}</div>
                    </main>
                    {/* </SessionProvider> */}
                    {/* </ReduxProvider> */}
                </SWRProvider>
            </body>
        </html>
    );
}
