import type { Metadata } from 'next';
import ReduxProvider from '@/providers/ReduxProvider';
import store from '@/redux/store';

//! 一些配置文件 网站清单的内容
export const metadata: Metadata = {
  title: '1Create Next App',
  description: '1Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ReduxProvider>
      <main className="py-24 px-2">
        <div className="container m-auto">{children}</div>
      </main>
    </ReduxProvider>
  );
}
